global:
  imageNamePrefix: "svrnm"
  imageNameSuffix: "0.2.0"

services:
  service-a:
    type: java
    endpoints: 
      http:
        /call/b:
          - http://service-b/sleep
  service-b:
    type: java
    endpoints: 
      http:
        /sleep:
          - slow,256
databases:

loaders:
  default:
    type: curl
    wait: 15
    count: 5
    urls:
      - http://service-a/call/b
      - http://service-b/sleep