global:
  imageNameSuffix: edge

services:
  service-a:
    type: java
    endpoints: 
      http:
        /call/b:
          - http://service-b/sleep
  service-b:
    type: java
    endpoints: 
      http:
        /sleep:
          - slow,256
databases:

loaders:
  default:
    type: curl
    wait: 0
    urls:
      - http://service-a/call/b
      - http://service-b/sleep