services:
  ## services
  service-a:
    image: svrnm/app-simulator-services-java:0.2.0
    volumes:
      - service_a_config:/config.json
  service-b:
    image: svrnm/app-simulator-services-java:0.2.0
    volumes:
      - service_b_config:/config.json
  ## loaders
  default:
    image: svrnm/app-simulator-loaders-curl:0.2.0
    volumes:
      - default_config:/config.json
configs:
  service_a_config:
    content: |
      {"endpoints": {"http": {"/call/b": ["http://service-b/sleep"]}}, "type": "java"}
  service_b_config:
    content: |
      {"endpoints": {"http": {"/sleep": ["slow,256"]}}, "type": "java"}