services:
  ## services
  service-a:
    image: ghcr.io/cisco-open/app-simulator-services-java:edge
    environment:
      APP_SERVER_PORT: "80"
    cap_add:
      - NET_BIND_SERVICE
    configs:
      - source: service_service_a_config
        target: /config.json
  service-b:
    image: ghcr.io/cisco-open/app-simulator-services-java:edge
    environment:
      APP_SERVER_PORT: "80"
    cap_add:
      - NET_BIND_SERVICE
    configs:
      - source: service_service_b_config
        target: /config.json
  ## loaders
  default:
    image: ghcr.io/cisco-open/app-simulator-loaders-curl:edge
    configs:
      - source: loader_default_config
        target: /config.json
configs:
  service_service_a_config:
    content: |
      {"endpoints": {"http": {"/call/b": ["http://service-b/sleep"]}}, "type": "java"}
  service_service_b_config:
    content: |
      {"endpoints": {"http": {"/sleep": ["slow,256"]}}, "type": "java"}
  loader_default_config:
    content: |
      {"count": 5, "type": "curl", "urls": ["http://service-a/call/b", "http://service-b/sleep"], "wait": 15}