services:

  frontend:
    image: java
    ports:
      - "3000:8080"
    volumes:
      - /config.json:/config.json
    environment:
      CONFIG_CONTENT: |
        {
  "agent": true,
  "endpoints": {
    "http": {
      "/upload": [
        "http://processing/magicByte",
        "http://processing/virus"
      ]
    }
  },
  "port": 3000,
  "type": "java"
}

  processing:
    image: java
    ports:
      - ":8080"
    volumes:
      - /config.json:/config.json
    environment:
      CONFIG_CONTENT: |
        {
  "agent": true,
  "endpoints": {
    "http": {
      "/magicByte": [
        "cache,128",
        {
          "call": "data",
          "id": "magicByteCheck",
          "type": "string",
          "value": [
            true,
            false
          ]
        }
      ],
      "/virus": [
        "http://virus-scanner/scan",
        {
          "call": "data",
          "id": "virusFoundScore",
          "type": "int",
          "value": [
            0,
            1,
            5,
            10
          ]
        }
      ]
    }
  },
  "type": "java"
}

  virus-scanner:
    image: nodejs
    ports:
      - "3001:8080"
    volumes:
      - /config.json:/config.json
    environment:
      CONFIG_CONTENT: |
        {
  "agent": false,
  "endpoints": {
    "http": {
      "scan": [
        "sleep,1500",
        {
          "call": "error,500,Scan failed",
          "probability": 0.1
        },
        "sleep,500"
      ]
    }
  },
  "port": 3001,
  "type": "nodejs"
}


  browser:
    image: puppeteer
    environment:
      CONFIG_CONTENT: |
        {
  "count": 3,
  "type": "puppeteer",
  "urls": [
    "http://frontend/upload",
    "http://frontend/upload",
    "http://frontend/upload"
  ],
  "wait": 15
}

