---
services:
  web-frontend:
    type: java
    port: 8888
    endpoints:
      http:
        /login:
          - http://accountservices/account/login
        /homepage:
          - http://accountservices/account/home
          - cache,128
        /getquote:
          - http://accountservices/quote
        /submitquote:
          - http://accountservices/submitquote
        /history:
          - http://accountservices/policies
        /startclaim:
          - http://accountservices/startclaim
        /submitclaim:
          - http://accountservices/submitclaim
        /processpolicy:
          - http://accountservices/policies/process
        /healthz:
          - slow,524
          - call: error,500,Oops
            probability: 0.1
  accountservices:
    type: java
    endpoints:
      http:
        /account/login:
          - slow,323
        /account/home:
          - slow,524
          - call: error,500,Oops
            probability: 0.1
        /quote:
          - http://quotesengine/quote
          - http://quotesengine/query/quote
        /policies:
          - http://policymgt/query/policy
        /submitquote:
          - http://quotesengine/query/quote
        /startclaim:
          - http://claimservices/startclaim
        /submitclaim:
          - http://claimservices/submitclaim
        /policies/process:
          - http://policymgt/query/policy
          - http://policymgt/processpolicy
  claimservices:
    type: java
    endpoints:
      http:
        /startclaim:
          - slow,725
        /submitclaim:
          - slow,623
  policymgt:
    type: java
    port: 3007
    endpoints:
      http:
        /query/policy:
          - sql://policiesdb/policy?query=INSERT INTO policies(customer,coverage) VALUES(test,123)
          - call: slow,9435
            probability: 0.13
        /processpolicy:
          -call: slow,926
  quotesengine:
    type: java
    port: 3008
    endpoints:
      http:
        /query/quote:
          - sql://quotesdb/quote?query=SELECT * FROM quotes
        /quote:
          - http://aggregator/aggregate
  aggregator:
    type: java
    endpoints:
      http:
        /aggregate:
          - http://carinsurance/quote
          - http://policygenius/quote
          - http://selectquote/quote
  selectquote:
    type: java
    endpoints:
      http:
        quote:
          - call: sleep, 4253
            schedule: "*/5 * * * *"
            probability: 0.37
  policygenius:
    type: java
    endpoints:
      http:
        quote:
          - call: sleep, 75
  carinsurance:
    type: java
    endpoints:
      http:
        quote:
          - call: sleep, 53

loaders:
  browser:
    type: puppeteer
    wait: 15
    count: 5
    urls:
      - http://web-frontend/login
      - http://web-frontend/homepage
      - http://web-frontend/getquote
      - http://web-frontend/homepage
      - http://web-frontend/history
      - http://web-frontend/startclaim
      - http://web-frontend/submitclaim
      - http://web-frontend/processpolicy
