---
name: Build and publish release container images
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    uses: ./.github/workflows/reusable-build-container-images.yml
    with:
      push: true
    secrets: inherit
