---
name: Build and publish release container images
on:
  push:
    tags:
      - "v*.*.*"

# Declare default permissions as read-only
permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-build-container-images.yml
    with:
      push: true
    secrets: inherit
