---
name: Build and publish dev container images
on:
  push:
    branches: [main]
    paths:
      - "src/loaders/**"
      - "src/services/**"
      - "src/databases/**"
      - ".github/workflows/reusable-build-container-images.yml"
      - ".github/workflows/build-images-on-commit.yml"
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/reusable-build-container-images.yml
    with:
      push: true
    secrets: inherit
