---
name: lint
on:
  push:
    # Run superlinter on pushes to default branch
    branches:
      - main
  # Run superlinter on pull request events
  pull_request_target:

# Declare default permissions as read-only
permissions: read-all

jobs:
  super-linter:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: 🧹 run superlinter
        uses: super-linter/super-linter@e1cb86b6e8d119f789513668b4b30bf17fe1efe4 # v7.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: '.'
          YAML_CONFIG_FILE: '.yamllint.yml'
          VALIDATE_GIT_COMMITLINT: false
          VALIDATE_ALL_CODEBASE: false
          MULTI_STATUS: false
