name: Build and publish nightly container images

on:
    schedule:
        - cron: '3 4 * * *'

jobs:
    build:
        uses: ./.github/workflows/reusable-build-container-images.yml
        with:
            push: true
            release_stream: nightly
        secrets: inherit