---
on:
  workflow_call:
    inputs:
      push:
        description: Set to true to push images to registries
        default: false
        required: false
        type: boolean
      registry_ghcr:
        description: github container registry
        default: "ghcr.io/cisco-open/app-simulator"
        required: false
        type: string

# Declare default permissions as read-only
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        image:
          - context: ./src/loaders/curl
            name: loaders-curl
          - context: ./src/services/java
            name: services-java
          - context: ./src/services/nodejs
            name: services-nodejs
          - context: ./src/services/dotnetcore
            name: services-dotnetcore
          - context: ./src/databases/mysql
            name: databases-mysql
          - context: ./scripts/generators/docker-compose
            name: generators-docker-compose
          - context: ./scripts/generators/k8s
            name: generators-k8s
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ inputs.registry_ghcr }}-${{ matrix.image.name }} # e.g. ghcr.io/cisco-open/app-simulator-loaders-curl
          # build nightly releases on schedule
          # build semver releases on tag
          # build edge releases on main branch
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=semver,pattern={{ version }}
            type=edge,branch=main
          labels: |

      - name: Log into GitHub Container Registry
        if: ${{ inputs.push }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: cisco-service
          password: ${{ secrets.PACKAGE_PUBLICATION_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3.4.0
        with:
          platforms: arm64, amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0
      - name: Build and push images
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: ${{ matrix.image.context }}
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push }}
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
